---
title: "Analiza palenia, PKB i akcyzy w Europie"
author: "Filip Kasprzycki"
date: "2025-11-16"
output:
  ioslides_presentation:
    css: mystyle.css
    widescreen: true
---

**Źródło danych:** Eurostat

```{r setup, include=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(GGally)

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)

# ---- Wczytanie danych ----
dane1 <- read_excel("Tobacco_consumption_HLTH2022-2.xlsx", sheet = "T1")
OdsetekPalacy <- dane1[,1:2] %>% rename(Country = 1, Smokers = 2)

dane2 <- read_excel("Europe_Population.xlsx")
PopulacjaKraju <- dane2[,1:2] %>% rename(Country = 1, Population = 2)

dane3 <- read_excel("europe_gdp_per_capita_2019.xlsx")
PKBKraju <- dane3[,1:2] %>% rename(Country = 1, GDP_per_capita = 2)

dane4 <- read_excel("Direct-taxes.xlsx", skip = 5, col_names = FALSE, sheet = "Table 13")
AkcyzaPKB <- dane4[,c(1,5)]
AkcyzaPKB <- AkcyzaPKB[1:(nrow(AkcyzaPKB)-6),]
names(AkcyzaPKB) <- c("Country","Excise_share_GDP")

# ---- Łączenie danych ----
kraje <- Reduce(intersect,
                list(OdsetekPalacy$Country,
                     PopulacjaKraju$Country,
                     PKBKraju$Country,
                     AkcyzaPKB$Country))

dane_final <- OdsetekPalacy %>%
  filter(Country %in% kraje) %>%
  left_join(PopulacjaKraju, by="Country") %>%
  left_join(PKBKraju, by="Country") %>%
  left_join(AkcyzaPKB, by="Country")

head(dane_final)
#Korelajca
cor1 <- cor(dane_final$Excise_share_GDP, dane_final$GDP_per_capita, use="complete.obs")
ggplot(dane_final, aes(GDP_per_capita, Excise_share_GDP)) +
geom_point(color="blue") +
geom_smooth(method="lm", se=FALSE, color="red") +
labs(title = paste0("Korelacja: ", round(cor1,2)))

ggplot(dane_final, aes(Excise_share_GDP, Smokers)) +
geom_point(color="darkgreen") +
geom_smooth(method="lm", se=FALSE, color="red") +
labs(title="Akcyza a odsetek palących")

cor3 <- cor(dane_final$GDP_per_capita, dane_final$Smokers, use="complete.obs")
ggplot(dane_final, aes(GDP_per_capita, Smokers)) +
geom_point(color="purple") +
geom_smooth(method="lm", se=FALSE, color="red") +
labs(title=paste0("PKB vs palenie (r=",round(cor3,2),")"))

model <- lm(Smokers ~ GDP_per_capita + Excise_share_GDP, data=dane_final)
summary(model)
